### ISSUE TITLE
[Quilt/1.20] Crash opening Mod Options

### ISSUE THREAD

**Issue by SAJewers** [juancarloscp52/spyglass-improvements#24]
[crash-2023-06-13_15.36.27-client.txt](https://github.com/juancarloscp52/spyglass-improvements/files/11738099/crash-2023-06-13_15.36.27-client.txt)

**Comment by SettingDust** [comment]
Same with 1.20.1 fabric https://mclo.gs/ILkN7j4
`NullPointerException: Cannot invoke "me.juancarloscp52.spyglass_improvements.client.SpyglassSliderWidget$MessageSupplier.updateMessage(me.juancarloscp52.spyglass_improvements.client.SpyglassSliderWidget, String, double)" because "this.messageSupplier" is null`

**Comment by fin600** [comment]
Exact same crash on 1.20.4

**Comment by juancarloscp52** [comment]
> [crash-2023-06-13_15.36.27-client.txt](https://github.com/juancarloscp52/spyglass-improvements/files/11738099/crash-2023-06-13_15.36.27-client.txt)

caused by Visual Overhaul fixed by them in version 5.1.0
